mongodb:
  restart: always
  image: sameersbn/mongodb:latest
  volumes:
    - /debugerr/mongodb:/var/lib/mongodb
  environment:
    - TZ=Asia/Bangkok
mysql:
  restart: always
  image: mysql/mysql-server:5.7
#  hostname: mysql
#  ports:
#    - "20410:3306"
  volumes:
    - /debugerr/mysql/data:/var/lib/mysql
    - /debugerr/mysql/mysql.cnf:/etc/mysql/my.cnf
  environment:
    - MYSQL_USER=debugerr
    - MYSQL_ROOT_PASSWORD=de!3UG
    - TZ=Asia/Bangkok
redis:
  restart: always
  image: redis:3.0.7
  hostname: redis
# ports:
#   - "6379:6379"
  volumes:
    - /debugerr/redis/data:/data
    - /debugerr/redis/redis.cnf:/usr/local/etc/redis/redis.conf
  environment: 
    - TZ=Asia/Bangkok

sentinel:
  restart: always
  image: node:5.10.0
  hostname: sentinel
  container_name: sentinel
  command: node /data/app/app.js
  links:
    - mysql:local-mysql
    - mongodb:local-mongodb
  ports:
    - '80:810'
    
#    - '811:811'
  volumes:
    - '/debugerr/:/data/app'
    - '/data/debugerr-source:/data/source'
    - '/data/debugerr-package:/data/package'
    - '/data/debugerr-content:/data/content'
  environment:
    - TZ=Asia/Bangkok

debugerr:
  restart: always
  image: node:0.10.44
  hostname: debugerr
  container_name: debugerr
  command: node /debugerr/bundle/main.js
  links:
    - mysql:local-mysql
    - mongodb:local-mongodb
    - sentinel:local-sentinel
#  ports:
#    - '8220:3000'
  volumes:
    - '/data/app-bundle:/app'
  environment:
#    - ROOT_URL=http://dev.ns.co.th
    - MONGO_URL=mongodb://local-mongodb:27017/debugerr
    - METEOR_SETTINGS={ "production":true, "public":{}, "private":{}, "mysql":{} }
    - METEOR_CONFIG=default
    - PORT=3000
    - TZ=Asia/Bangkok